num1,num2=int(input("Enter a frist number is:-")),int(input("Enter a second number is:-"))
print(num1,"==",num2,"is:-",(num1==num2))
print(num1,">",num2,"is:-",(num1>num2))
print(num1,"<",num2,"is:-",(num1<num2))
print(num1,"!=",num2,"is:-",(num1!=num2))
print(num1,">=",num2,"is:-",(num1>=num2))
print(num1,"<=",num2,"is:-",(num1<=num2))