a=int(input("Enter a value for a is:-"))
b=int(input("Enter a value for b is:-"))
print("Addition of",a,"and",b,"is:-",a+b)
print("Substraction of",a,"and",b,"is:-",a-b)
print("Multiplication of",a,"and",b,"is:-",a*b)
print("Division of",a,"and",b,"is:-",a/b)
print("Reminder of",a,"and",b,"is:-",(a%b))
print("Floor Division of",a,"and",b,"is:-",a//b)
print("expontion of",a,"and",b,"is:-",(a**b))