a=input("Enter a string for a:-")
b=input("Enter a string for b:-")
print("a>b is:-",(a>b))
print("a<b is:-",(a<b))
print("a>=b is:-",(a>=b))
print("a<=b is:-",(a<=b))
print("a==b is:-",(a==b))
print("a!=b is:-",(a!=b))
print("string concatination is:-",a+b)
print("* operator useing string is:-",a*5)