print("Enter a three value are:-")
a,b,c=int(input("a=")),int(input("b=")),int(input("c="))
print(a,b,c)
print("seperator(sep='') function:-",a,b,c,sep=";")
print(a,b,c,sep=':')
print("end function used in sring")
print("hello",end=":")
print("omkar",end=":")
print("jadhav",end=":")